services:
  api:
    image: dronavocab/livekit-flow:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livekit-api
    command: ["python", "-m", "api.main"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  agent:
    image: somashaker23/ltfs-agent-pl:latest
    container_name: livekit-agent
    command: ["python", "agent/web_rtc_server.py", "dev"]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - api
