services:
  gemma-api:
    build: .
    image: kashyapsai2003/gemma_inhouse:without_openai
    container_name: gemma-api
    ports:
      - "6000:6000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - TRANSFORMERS_VERBOSITY=info
    volumes:
      - hf_cache:/data/hf_cache
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  hf_cache:
    driver: local
